<!DOCTYPE html>
<html>
<head>
  <title></title>
  </head>
<body>
<hr class="bg-danger" style="height:1px">
 <div class="container-fluid mt-5 mb-5">
      <div class="row-equal">

          <div class="owl-carousel"  id="categorias">

            <a href="categorias/informatica/hardwere.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/1.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Hardwere</p>
              </div>
            </a>

            <a href="categorias/informatica/perifericos.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/2.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Perifericos</p>
              </div>
            </a>

            <a href="categorias/informatica/computadores.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/3.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Computadores</p>
              </div>
            </a>

            <a href="categorias/informatica/notebooks.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/4.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Notebooks</p> 
              </div>
            </a>

            <a href="categorias/informatica/acessorios.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/5.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Acessórios</p>
              </div>
            </a>


            <a href="categorias/eletronicos/smartphones.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/6.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Smartphones</p> 
              </div>
            </a>

            <a href="categorias/eletronicos/smatwatches.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/7.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Smartwatches</p>
              </div>
            </a>

            <a href="categorias/eletronicos/drones.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/8.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Drones</p>
              </div>
            </a>

            <a href="categorias/eletronicos/componentes.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/9.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Componentes</p>
              </div>
            </a>

            <a href="categorias/games/consoles.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/10.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Consoles</p>
              </div>
            </a>

            <a href="categorias/games/jogos.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/11.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Jogos</p>
              </div>
            </a>

            <a href="categorias/leitura/hqs.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/12.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">HQs</p>
              </div>
            </a>

            <a href="categorias/leitura/mangas.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/13.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Mangás</p>
              </div>  
            </a>

            <a href="categorias/leitura/livrso.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/14.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Livros</p>
              </div>
            </a>

            <a href="categorias/leitura/ebooks.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/15.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">E-books</p>
              </div>
            </a>

            <a href="categorias/vestuario/masculino.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/16.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Vestúario</p>
              </div>
            </a>


             <a href="categorias/vestuario/calcados.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/17.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Calçados</p>
              </div>
            </a>

            <a href="categorias/vestuario/acessorios.php" style="text-decoration: none;">
              <div class="item">
                <img src="img/categorias/18.jpg">
                <p class="text-center text-dark" style="font-family: cursive;">Itens</p>
              </div>
            </a>

          </div>

      </div> 
    </div>  


<script>
  $('#categorias').owlCarousel({
              loop:true,
              margin:-750,
              responsive:{
              0:{
                  items:1,
                  margin:10,
                  autoWidth:true,
              },
              1000:{
                  margin:100,
                  autoWidth:true,
              },
              2000:{
                items:4,
                  margin:80,
                  autoWidth:true,
              }
    }
})
</script> 
</body>
</html>
 