<?php
    include "includes/localizacao.inc";
?>



<link rel="stylesheet" href="css/footer.css">

<div class="footer" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3>Categorias</h3>
                    <ul>
                        <li> <a href="informatica.php">Informática</a> </li>
                        <li> <a href="eletronicos.php">Eletrônicos</a> </li>
                        <li> <a href="games.php">Games</a> </li>
                        <li> <a href="livros.php">Livros</a> </li>
                        <li> <a href="moda.php">Moda</a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3>Intitucional</h3>
                    <ul>
                        <li> <a href="sobre.php">Quem Somos</a> </li>
                        <li> <a data-toggle="modal" data-target="#local" href="#">Localização</a></li>
                        <li> <a href="#">Politica de Privacidade</a> </li>
                        <li> <a href="#">Politicas do Site</a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3>Suporte</h3>
                    <ul>
                        <li> <a href="#">Como Comprar</a> </li>
                        <li> <a href="#">Entrega</a> </li>
                        <li> <a href="pagamentos.php">Formas de Pagamento</a> </li>
                        <li> <a href="#">Garantia</a> </li>
                        <li> <a href="#">Troca e Devolução</a> </li>
                        <li> <a href="contato.php">Fale Conosco</a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3>Atendimento</h3>
                    <p style="font-size: 13px; color:#78828D">Horário de atendimento: 09:00 às 19:00 de segunda à sexta-feira, horário de Brasília (exceto feriados)</p>
                </div>
                <div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
                    <h3>Novidades</h3>
                    <ul>
                        <li>
                            <form method="post" action="subscribe.php">
                                <div class="input-append newsletter-box text-center">
                                    <input type="email" class="full text-center" placeholder="Email">
                                    <button class="btn  btn-dark" type="submit">Cadastrar</button>
                                </div>
                            </form>
                        </li>
                    </ul>
                    <ul class="social">
                        <li><a href="https://facebook.com/" target="blank"><i class="fab fa-facebook-f fa-2x"></i></a></li>
                        <li><a href="https://twitter.com/" target="blank"><i class="fab fa-twitter fa-2x"></i> </a></li>
                        <li><a href="https://plus.google.com/" target="blank"><i class="fab fa-google-plus fa-2x"></i></a></li>
                        <li><a href="https://instagram.com/" target="blank"><i class="fab fa-instagram fa-2x"></i></a></li>
                    </ul>
                </div>
            </div>
            <!--/.row--> 
        </div>
        <!--/.container--> 
    </div>
    <!--/.footer-->
    
        
    <div class="footer-bottom">
        <div class="container pb-2">
                <div class="pull-right" style="font-size:1.5em;">
                    <i class="fab fa-cc-visa"></i>
                    <i class="fab fa-cc-mastercard"></i>
                    <i class="fas fa-barcode"></i>
                    <i class="fab fa-paypal"></i>
                </div>
            <p class="text-center"> Copyright © ACCIO - 2018. All right reserved. </p>

            </div>
        </div>
    </div>

